### ISSUE TITLE
Line numbers in list item code blocks show as a., b., c., etc.

### ISSUE THREAD

**Issue by trailjeep** [ssahara/dw-plugin-extlist#5]
Using DW default line numbering - not a plugin.
I had to add to userall.css:
```css
.extlist pre.code ol    { list-style: decimal; }
.extlist pre.code ol li { display: list-item; }
```
