### ISSUE TITLE
Alphabetical ordered list

### ISSUE THREAD

**Issue by vaniwiki** [ssahara/dw-plugin-extlist#7]
Though not mentioned on the plugin page, i found the example from the plugin’s css.

`~~ol:alphabet~~`

But it doesn’t seem to work. Is there a trick to it, or is it just not working?

**Comment by fiwswe** [comment]
It was broken, but #17 fixes it.

**Comment by fiwswe** [comment]
Alternative:

It may be better to deal with this using CSS only. I.e. using [@counter-style](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/At-rules/@counter-style). That would remove all of the related PHP code. And it would allow for markers such as `(aa)` for values > 26.

For example the replicates the current (intended) behaviour:
```css
@counter-style alphabet {
  system: fixed;
  symbols: ⒜ ⒝ ⒞ ⒟ ⒠ ⒡ ⒢ ⒣ ⒤ ⒥ ⒦ ⒧ ⒨ ⒩ ⒪ ⒫ ⒬ ⒭ ⒮ ⒯ ⒰ ⒱ ⒲ ⒳ ⒴ ⒵;
  suffix: " ";
}

ol.alphabet {
  list-style-type: alphabet;
}
```

Or better yet, allow for `(aa)` etc.:
```css
@counter-style alphabet {
  system: alphabetic;
  symbols: a b c d e f g h i j k l m n o p q r s t u v w x y z;
  prefix: "(";
  suffix: ") ";
}

ol.alphabet {
  list-style-type: alphabet;
}
```

The only drawback to this solution is https://github.com/splitbrain/lesserphp/issues/5. So the `@counter-style` rule must be placed in `…/conf/meta.html` to work. Not very  good for plugin distribution and management :-(
